var searchData=
[
  ['c_20arduino_20libraries_0',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md5',1,'']]],
  ['c_20c_20on_20micro_20controllers_1',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['c_20code_2',['Runtime collaboration with C++ code',['../index.html#autotoc_md14',1,'']]],
  ['c_20code_20to_20lamblisp_3',['Adding native C++ code to LambLisp.',['../index.html#autotoc_md51',1,'']]],
  ['c_20on_20micro_20controllers_4',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['called_20lamblisp_20instead_20of_20scheme_5',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md67',1,'']]],
  ['calls_6',['Tail recursion and tail-calls',['../index.html#autotoc_md12',1,'']]],
  ['cell_7',['Cell',['../classCell.html',1,'']]],
  ['cell_20memory_20model_20and_20list_20structures_8',['Cell Memory Model and List Structures',['../index.html#autotoc_md31',1,'']]],
  ['cell_5fname_9',['cell_name',['../classCell.html#a29b39708a4fa37c77baaee15653f27e9',1,'Cell']]],
  ['chezscheme_20and_20chicken_10',['What makes LambLisp different from small Lisps, such as Picobit and uLisp, or big Lisps, such as racket, ChezScheme, and chicken?',['../index.html#autotoc_md58',1,'']]],
  ['chicken_11',['What makes LambLisp different from small Lisps, such as Picobit and uLisp, or big Lisps, such as racket, ChezScheme, and chicken?',['../index.html#autotoc_md58',1,'']]],
  ['class_20data_20types_12',['Procedures are first-class data types',['../index.html#autotoc_md13',1,'']]],
  ['class_20hierarchical_20dictionaries_13',['First-class hierarchical dictionaries',['../index.html#autotoc_md9',1,'']]],
  ['classes_20dictionaries_20and_20objects_14',['Hash tables, environments, classes, dictionaries, and objects',['../index.html#autotoc_md46',1,'']]],
  ['code_15',['Runtime collaboration with C++ code',['../index.html#autotoc_md14',1,'']]],
  ['code_20to_20lamblisp_16',['Adding native C++ code to LambLisp.',['../index.html#autotoc_md51',1,'']]],
  ['collaboration_20with_20c_20code_17',['Runtime collaboration with C++ code',['../index.html#autotoc_md14',1,'']]],
  ['collection_18',['Garbage Collection',['../index.html#autotoc_md32',1,'']]],
  ['collection_19',['Adaptive real-time garbage collection',['../index.html#autotoc_md6',1,'']]],
  ['collector_20',['Adaptive Real-Time Garbage Collector',['../index.html#autotoc_md63',1,'']]],
  ['combination_20with_20c_20c_20on_20micro_20controllers_21',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['compatibility_20matrix_22',['LambLisp Compatibility Matrix',['../index.html#autotoc_md54',1,'']]],
  ['compilation_23',['compilation',['../index.html#autotoc_md10',1,'Incremental, just-in-time compilation'],['../index.html#autotoc_md38',1,'Scaling by incremental compilation']]],
  ['compiler_20organization_24',['Interpreter &amp;amp; compiler organization',['../index.html#autotoc_md25',1,'']]],
  ['cons_25',['cons',['../classLamb.html#a36f015662ed557d84c2a711a43f34887',1,'Lamb']]],
  ['continuation_20passing_20style_26',['Tail recursion and Continuation-Passing Style',['../index.html#autotoc_md64',1,'']]],
  ['control_27',['Real-time control',['../index.html#autotoc_md3',1,'']]],
  ['control_20applications_20as_20virtual_20machines_28',['Control Applications as Virtual Machines.',['../index.html#autotoc_md27',1,'']]],
  ['control_20system_29',['What is a real-time control system?',['../index.html#autotoc_md56',1,'']]],
  ['controllers_30',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['controlling_20memory_20allocation_31',['Scaling up or down by controlling memory allocation.',['../index.html#autotoc_md36',1,'']]],
  ['coverage_32',['Scheme R5RS coverage',['../index.html#autotoc_md62',1,'']]],
  ['currently_20implemented_20features_33',['What are the currently implemented features?',['../index.html#autotoc_md61',1,'']]]
];
