var searchData=
[
  ['a_20—_20reach_0',['Group A — Reach',['../index.html#autotoc_md46',1,'']]],
  ['a_20coverage_20plan_1',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['a_20guard_20that_20means_20has_20a_20socket_20must_20now_20say_20so_2',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md200',1,'']]],
  ['a_20hierarchical_20dictionary_3',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['a_20jetson_20or_20raspberry_20pi_20libgpiod_4',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['a_20master_5',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['a_20nutshell_6',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md16',1,'']]],
  ['a_20peripheral_7',['3.1 Opening a Peripheral',['../index.html#modbus-peripheral-open',1,'']]],
  ['a_20pin_8',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['a_20real_20time_20control_20system_9',['What is a real-time control system?',['../index.html#autotoc_md169',1,'']]],
  ['a_20slave_10',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['a_20socket_20must_20now_20say_20so_11',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md200',1,'']]],
  ['aarch64_12',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['access_20point_20softap_13',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['accessors_14',['3.3 Register Accessors',['../index.html#modbus-register-accessors',1,'']]],
  ['accumulator_20floor_20map_20scm_15',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['acknowledgements_16',['Acknowledgements',['../index.html#autotoc_md198',1,'']]],
  ['actually_20drives_20a_20pin_17',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['adaptive_20real_20time_20garbage_20collection_18',['Adaptive real-time garbage collection',['../index.html#autotoc_md22',1,'']]],
  ['addressable_20led_20strip_20neopixel_19',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md94',1,'']]],
  ['addressable_20leds_20ws2812_20scm_20',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md99',1,'']]],
  ['advanced_21',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_22',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['ai_20and_20machine_20to_20machine_23',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['ai_20orchestration_20and_20the_20robot_20stack_24',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['air_20updates_25',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['air_20updates_20without_20reboot_26',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['algebra_27',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['all_20platforms_28',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md177',1,'']]],
  ['an_20rtos_29',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md195',1,'']]],
  ['and_20aarch64_30',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['and_20arq_20llip_20serial_20scm_31',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['and_20ascii_20render_32',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['and_20boards_33',['Supported Platforms and Boards',['../index.html#autotoc_md9',1,'']]],
  ['and_20c_20api_34',['Language Internals and C++ API',['../index.html#autotoc_md53',1,'']]],
  ['and_20collisions_35',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['and_20conformance_36',['Language and Conformance',['../index.html#autotoc_md179',1,'']]],
  ['and_20development_20tools_37',['Diagnostics and Development Tools',['../index.html#autotoc_md71',1,'']]],
  ['and_20evaluation_38',['Environments and Evaluation',['../index.html#autotoc_md149',1,'']]],
  ['and_20flash_39',['Build and Flash',['../index.html#autotoc_md12',1,'']]],
  ['and_20gc_20tuning_40',['and GC Tuning',['../index.html#arch-adaptive',1,'Memory and GC Tuning'],['../index.html#gc-tuning',1,'Runtime and GC Tuning']]],
  ['and_20global_20control_41',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['and_20hashing_20details_42',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['and_20list_20structures_43',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['and_20lists_44',['Pairs and Lists',['../index.html#autotoc_md137',1,'']]],
  ['and_20machine_20to_20machine_45',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['and_20macro_46',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['and_20memory_20tuning_47',['GC and memory tuning',['../index.html#autotoc_md79',1,'']]],
  ['and_20motors_20pca9685_20scm_48',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md98',1,'']]],
  ['and_20naming_49',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['and_20non_20symbol_20keys_50',['Objects and non-symbol keys',['../index.html#autotoc_md61',1,'']]],
  ['and_20on_20board_20display_20esp32_20s3_20eye_51',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['and_20operation_52',['Integration and Operation',['../index.html#autotoc_md190',1,'']]],
  ['and_20output_53',['Input and Output',['../index.html#autotoc_md153',1,'']]],
  ['and_20pre_20reserve_54',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['and_20profinet_20interface_55',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['and_20scheme_56',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['and_20start_20the_20car_57',['6.2 Flash and Start the Car',['../index.html#fwd-run-car',1,'']]],
  ['and_20system_58',['Timing and system',['../index.html#autotoc_md78',1,'']]],
  ['and_20tail_20calls_59',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['and_20the_20robot_20stack_60',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['and_20what_20actually_20drives_20a_20pin_61',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['and_20what_20is_20not_62',['What is the same as Linux, and what is not',['../index.html#autotoc_md7',1,'']]],
  ['and_20why_20it_20exists_63',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['any_20directory_64',['Running from any directory',['../index.html#autotoc_md6',1,'']]],
  ['api_65',['API',['../index.html#profinet-api',1,'5.2 The API'],['../index.html#autotoc_md53',1,'Language Internals and C++ API']]],
  ['api_20for_20new_20lisp_20primitives_66',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md23',1,'']]],
  ['api_20llip_20client_20scm_67',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md85',1,'']]],
  ['applications_20as_20virtual_20machines_68',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['arbitrary_20precision_20integers_20bignums_69',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['architecture_70',['Role in the Supervisory Architecture',['../index.html#autotoc_md88',1,'']]],
  ['architecture_20internals_71',['LambLisp Architecture Internals',['../index.html#autotoc_md32',1,'']]],
  ['architecture_20notes_72',['7. Architecture Notes',['../index.html#fwd-arch-notes',1,'']]],
  ['arduino_20embedded_20i_20o_73',['Arduino / Embedded I/O',['../index.html#llarduino',1,'']]],
  ['arduino_20libraries_74',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md21',1,'']]],
  ['are_20first_20class_20data_20types_75',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]],
  ['are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_76',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['are_20wrappers_20around_20hierarchical_20dictionaries_77',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['around_20hierarchical_20dictionaries_78',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['arq_20llip_20serial_20scm_79',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['array_80',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['array_20math_20linear_20algebra_81',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['arrays_20array_82',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['as_20a_20master_83',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['as_20a_20slave_84',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['as_20linux_20and_20what_20is_20not_85',['What is the same as Linux, and what is not',['../index.html#autotoc_md7',1,'']]],
  ['as_20modbus_20controller_86',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['as_20modbus_20peripheral_87',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['as_20the_20universal_20glue_88',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['as_20virtual_20machines_89',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['ascii_20render_90',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['asked_20questions_91',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['ast_20→_20bytecode_20→_20native_20code_92',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['asynchronous_20work_20—_20deferred_20task_20queue_93',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['at_20startup_94',['What Happens at Startup',['../index.html#autotoc_md14',1,'']]],
  ['autonomous_20fill_20behaviour_95',['3.3 Autonomous Fill Behaviour',['../index.html#fwd-autonomous',1,'']]],
  ['autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_96',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]]
];
