var searchData=
[
  ['c_20arduino_20libraries_0',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md5',1,'']]],
  ['c_20c_20on_20micro_20controllers_1',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['c_20code_2',['Runtime collaboration with C++ code',['../index.html#autotoc_md14',1,'']]],
  ['c_20code_20to_20lamblisp_3',['Adding native C++ code to LambLisp.',['../index.html#autotoc_md51',1,'']]],
  ['c_20on_20micro_20controllers_4',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['called_20lamblisp_20instead_20of_20scheme_5',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md67',1,'']]],
  ['calls_6',['Tail recursion and tail-calls',['../index.html#autotoc_md12',1,'']]],
  ['cell_20memory_20model_20and_20list_20structures_7',['Cell Memory Model and List Structures',['../index.html#autotoc_md31',1,'']]],
  ['chezscheme_20and_20chicken_8',['What makes LambLisp different from small Lisps, such as Picobit and uLisp, or big Lisps, such as racket, ChezScheme, and chicken?',['../index.html#autotoc_md58',1,'']]],
  ['chicken_9',['What makes LambLisp different from small Lisps, such as Picobit and uLisp, or big Lisps, such as racket, ChezScheme, and chicken?',['../index.html#autotoc_md58',1,'']]],
  ['class_20data_20types_10',['Procedures are first-class data types',['../index.html#autotoc_md13',1,'']]],
  ['class_20hierarchical_20dictionaries_11',['First-class hierarchical dictionaries',['../index.html#autotoc_md9',1,'']]],
  ['classes_20dictionaries_20and_20objects_12',['Hash tables, environments, classes, dictionaries, and objects',['../index.html#autotoc_md46',1,'']]],
  ['code_13',['Runtime collaboration with C++ code',['../index.html#autotoc_md14',1,'']]],
  ['code_20to_20lamblisp_14',['Adding native C++ code to LambLisp.',['../index.html#autotoc_md51',1,'']]],
  ['collaboration_20with_20c_20code_15',['Runtime collaboration with C++ code',['../index.html#autotoc_md14',1,'']]],
  ['collection_16',['Garbage Collection',['../index.html#autotoc_md32',1,'']]],
  ['collection_17',['Adaptive real-time garbage collection',['../index.html#autotoc_md6',1,'']]],
  ['collector_18',['Adaptive Real-Time Garbage Collector',['../index.html#autotoc_md63',1,'']]],
  ['combination_20with_20c_20c_20on_20micro_20controllers_19',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['compatibility_20matrix_20',['LambLisp Compatibility Matrix',['../index.html#autotoc_md54',1,'']]],
  ['compilation_21',['compilation',['../index.html#autotoc_md10',1,'Incremental, just-in-time compilation'],['../index.html#autotoc_md38',1,'Scaling by incremental compilation']]],
  ['compiler_20organization_22',['Interpreter &amp;amp; compiler organization',['../index.html#autotoc_md25',1,'']]],
  ['continuation_20passing_20style_23',['Tail recursion and Continuation-Passing Style',['../index.html#autotoc_md64',1,'']]],
  ['control_24',['Real-time control',['../index.html#autotoc_md3',1,'']]],
  ['control_20applications_20as_20virtual_20machines_25',['Control Applications as Virtual Machines.',['../index.html#autotoc_md27',1,'']]],
  ['control_20system_26',['What is a real-time control system?',['../index.html#autotoc_md56',1,'']]],
  ['controllers_27',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['controlling_20memory_20allocation_28',['Scaling up or down by controlling memory allocation.',['../index.html#autotoc_md36',1,'']]],
  ['coverage_29',['Scheme R5RS coverage',['../index.html#autotoc_md62',1,'']]],
  ['currently_20implemented_20features_30',['What are the currently implemented features?',['../index.html#autotoc_md61',1,'']]]
];
