var searchData=
[
  ['o_0',['Arduino / Embedded I/O',['../index.html#llarduino',1,'']]],
  ['object_20system_1',['Lightweight object system',['../index.html#autotoc_md62',1,'']]],
  ['objects_2',['Stateful Objects',['../index.html#autotoc_md64',1,'']]],
  ['objects_20and_20non_20symbol_20keys_3',['Objects and non-symbol keys',['../index.html#autotoc_md61',1,'']]],
  ['objects_20are_20wrappers_20around_20hierarchical_20dictionaries_4',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['oblist_5',['The oblist',['../index.html#autotoc_md60',1,'']]],
  ['of_20existing_20c_20arduino_20libraries_6',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md21',1,'']]],
  ['of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_7',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['of_20lisp_20and_20scheme_8',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['of_20scheme_9',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md180',1,'']]],
  ['of_20the_20freenove_204wd_20car_10',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md89',1,'']]],
  ['on_11',['What hardware does LambLisp run on?',['../index.html#autotoc_md162',1,'']]],
  ['on_20a_20jetson_20or_20raspberry_20pi_20libgpiod_12',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['on_20all_20platforms_13',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md177',1,'']]],
  ['on_20board_20car_20code_14',['3. On-Board Car Code',['../index.html#fwd-onboard',1,'']]],
  ['on_20board_20display_20esp32_20s3_20eye_15',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['on_20embedded_20hardware_16',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['on_20linux_17',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['on_20micro_20controllers_18',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['on_20the_20jetson_19',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['on_20windows_20',['Quick Start: Try LambLisp on Windows',['../index.html#quick-start-windows',1,'']]],
  ['onewire_201_20wire_20bus_21',['OneWire (1-Wire Bus)',['../index.html#onewire',1,'']]],
  ['open_20api_20for_20new_20lisp_20primitives_22',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md23',1,'']]],
  ['open_20source_23',['Is LambLisp open source?',['../index.html#autotoc_md164',1,'']]],
  ['opening_20a_20peripheral_24',['3.1 Opening a Peripheral',['../index.html#modbus-peripheral-open',1,'']]],
  ['opening_20the_20bus_25',['2.1 Opening the Bus',['../index.html#profibus-open',1,'']]],
  ['operation_26',['Operation',['../index.html#autotoc_md190',1,'Integration and Operation'],['../index.html#autotoc_md84',1,'The eval Operation']]],
  ['operations_27',['Operations',['../index.html#autotoc_md70',1,'Dictionary (Environment) Operations'],['../index.html#autotoc_md83',1,'Operations']]],
  ['or_20raspberry_20pi_20libgpiod_28',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['orchestration_20and_20the_20robot_20stack_29',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['organization_30',['Interpreter &amp;amp; compiler organization',['../index.html#arch-interp',1,'']]],
  ['other_20scheme_20implementations_31',['Other Scheme Implementations',['../index.html#competitors',1,'']]],
  ['output_32',['Input and Output',['../index.html#autotoc_md153',1,'']]],
  ['over_20the_20air_20updates_33',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['over_20the_20air_20updates_20without_20reboot_34',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['overview_35',['Overview',['../index.html#modbus-overview',1,'1. Overview'],['../index.html#fwd-overview',1,'1. Overview'],['../index.html#autotoc_md40',1,'Overview']]]
];
