var searchData=
[
  ['pairs_20and_20lists_0',['Pairs and Lists',['../index.html#autotoc_md137',1,'']]],
  ['parameters_1',['6.4 Tuning Parameters',['../index.html#fwd-run-tuning',1,'']]],
  ['patterns_2',['Device Patterns',['../index.html#autotoc_md65',1,'']]],
  ['pauses_3',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['pca9685_20pwm_20controller_4',['PCA9685 PWM Controller',['../index.html#autotoc_md93',1,'']]],
  ['pca9685_20scm_5',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md98',1,'']]],
  ['pcf8574_20scm_6',['I2C GPIO Expander (&lt;span class=&quot;tt&quot;&gt;PCF8574.scm&lt;/span&gt;)',['../index.html#autotoc_md103',1,'']]],
  ['peripheral_7',['Peripheral',['../index.html#modbus-peripheral',1,'3. LambLisp as Modbus Peripheral'],['../index.html#modbus-peripheral-open',1,'3.1 Opening a Peripheral']]],
  ['peripheral_20functions_8',['Peripheral Functions',['../index.html#autotoc_md112',1,'']]],
  ['peripheral_20summary_9',['Freenove 4WD Car Kit — Peripheral Summary',['../index.html#autotoc_md95',1,'']]],
  ['personality_20personality_20scm_10',['Personality (&lt;span class=&quot;tt&quot;&gt;Personality.scm&lt;/span&gt;)',['../index.html#autotoc_md121',1,'']]],
  ['personality_20scm_11',['Personality (&lt;span class=&quot;tt&quot;&gt;Personality.scm&lt;/span&gt;)',['../index.html#autotoc_md121',1,'']]],
  ['pi_20libgpiod_12',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['pin_13',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['pins_20on_20a_20jetson_20or_20raspberry_20pi_20libgpiod_14',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['plan_15',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['planner_16',['5.1 Boustrophedon Coverage Planner',['../index.html#fwd-cloud-planner',1,'']]],
  ['platform_17',['Multi-platform',['../index.html#autotoc_md19',1,'']]],
  ['platform_20a_20guard_20that_20means_20has_20a_20socket_20must_20now_20say_20so_18',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md200',1,'']]],
  ['platform_20notes_19',['4. Platform Notes',['../index.html#modbus-platform',1,'']]],
  ['platform_20support_20',['Multi-Platform Support',['../index.html#arch-multiplatform',1,'']]],
  ['platforms_21',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md177',1,'']]],
  ['platforms_20and_20boards_22',['Supported Platforms and Boards',['../index.html#autotoc_md9',1,'']]],
  ['point_20softap_23',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['poll_20model_24',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['ports_25',['Ports',['../index.html#autotoc_md151',1,'']]],
  ['pre_20reserve_26',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['precision_20integers_20bignums_27',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['prerequisites_28',['Prerequisites',['../index.html#autotoc_md2',1,'']]],
  ['preview_20layer_29',['eye-cam.scm live-preview layer',['../index.html#autotoc_md97',1,'']]],
  ['primitives_30',['3.2 Motion Primitives',['../index.html#fwd-motion',1,'']]],
  ['primitives_31',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md23',1,'']]],
  ['primitives_20c_32',['Camera / LCD primitives (C++)',['../index.html#autotoc_md96',1,'']]],
  ['procedures_33',['Stateless Procedures',['../index.html#arch-mop3',1,'']]],
  ['procedures_20are_20first_20class_20data_20types_34',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]],
  ['profibus_20and_20profinet_20interface_35',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['profibus_20dp_20as_20a_20master_36',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['profibus_20dp_20as_20a_20slave_37',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['profibus_20dp_20master_38',['PROFIBUS DP master',['../index.html#autotoc_md113',1,'']]],
  ['profibus_20dp_20slave_39',['PROFIBUS DP slave',['../index.html#autotoc_md114',1,'']]],
  ['profinet_40',['5. PROFINET',['../index.html#profinet',1,'']]],
  ['profinet_20interface_41',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['profinet_20io_20device_42',['PROFINET IO-Device',['../index.html#autotoc_md115',1,'']]],
  ['proprietary_20distribution_43',['Proprietary Distribution',['../index.html#autotoc_md67',1,'']]],
  ['protocol_44',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['pwm_20controller_45',['PCA9685 PWM Controller',['../index.html#autotoc_md93',1,'']]],
  ['python_20derivatives_46',['Why not use embedded Python derivatives?',['../index.html#autotoc_md186',1,'']]]
];
