var searchData=
[
  ['machine_0',['Machine',['../index.html#autotoc_md48',1,'AI and Machine-to-Machine'],['../index.html#arch-bc',1,'Bytecode Virtual Machine'],['../index.html#autotoc_md36',1,'LambLisp Virtual Machine']]],
  ['machine_20to_20machine_1',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['machines_2',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['macro_3',['macro',['../index.html#arch-lambda',1,'lambda, nlambda, and macro'],['../index.html#autotoc_md56',1,'macro']]],
  ['management_4',['Memory Management',['../index.html#autotoc_md39',1,'']]],
  ['map_5',['4.5 Collecting the Map',['../index.html#fwd-jetson-collect',1,'']]],
  ['map_20accumulator_20floor_20map_20scm_6',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['map_20scm_7',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['map_20store_20and_20ascii_20render_8',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['mapping_20demo_20telemetry_20scm_9',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md119',1,'']]],
  ['mapping_20with_20the_20freenove_204wd_20car_10',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['marshaling_11',['Data Marshaling',['../index.html#autotoc_md68',1,'']]],
  ['master_12',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['master_13',['PROFIBUS DP master',['../index.html#autotoc_md113',1,'']]],
  ['math_20linear_20algebra_14',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['matrix_15',['LambLisp Compatibility Matrix',['../index.html#compat-matrix',1,'']]],
  ['means_20has_20a_20socket_20must_20now_20say_20so_16',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md200',1,'']]],
  ['memory_20and_20gc_20tuning_17',['Memory and GC Tuning',['../index.html#arch-adaptive',1,'']]],
  ['memory_20and_20pre_20reserve_18',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['memory_20footprint_19',['What is the memory footprint?',['../index.html#autotoc_md197',1,'']]],
  ['memory_20management_20',['Memory Management',['../index.html#autotoc_md39',1,'']]],
  ['memory_20model_20and_20list_20structures_21',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['memory_20tuning_22',['GC and memory tuning',['../index.html#autotoc_md79',1,'']]],
  ['memory_20tuning_3a_20stack_20size_20dma_20memory_20and_20pre_20reserve_23',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['micro_20controllers_24',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['microprocessors_25',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['microsecond_20isr_26',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md44',1,'']]],
  ['modbus_20controller_27',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['modbus_20interface_28',['LambLisp Modbus Interface',['../index.html#modbus',1,'']]],
  ['modbus_20peripheral_29',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['modbus_20request_30',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md111',1,'']]],
  ['model_31',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['model_32',['model',['../index.html#profinet-device-model',1,'5.3 Device model'],['../index.html#autotoc_md75',1,'The boot-confirm / rollback model']]],
  ['model_20and_20list_20structures_33',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['module_34',['3.5 Bee Strategy Module',['../index.html#fwd-bee-onboard',1,'']]],
  ['motion_20primitives_35',['3.2 Motion Primitives',['../index.html#fwd-motion',1,'']]],
  ['motors_20pca9685_20scm_36',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md98',1,'']]],
  ['multi_20platform_37',['Multi-platform',['../index.html#autotoc_md19',1,'']]],
  ['multi_20platform_20support_38',['Multi-Platform Support',['../index.html#arch-multiplatform',1,'']]],
  ['music_20scm_39',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md120',1,'']]],
  ['musical_20notes_20music_20scm_40',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md120',1,'']]],
  ['must_20now_20say_20so_41',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md200',1,'']]]
];
