var searchData=
[
  ['a_20hierarchical_20dictionary_0',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#autotoc_md23',1,'']]],
  ['a_20nutshell_1',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md16',1,'']]],
  ['a_20real_20time_20control_20system_2',['What is a real-time control system?',['../index.html#autotoc_md56',1,'']]],
  ['acknowledgements_3',['Acknowledgements',['../index.html#autotoc_md68',1,'']]],
  ['adaptive_20real_20time_20garbage_20collection_4',['Adaptive real-time garbage collection',['../index.html#autotoc_md6',1,'']]],
  ['adaptive_20real_20time_20garbage_20collector_5',['Adaptive Real-Time Garbage Collector',['../index.html#autotoc_md63',1,'']]],
  ['adaptive_20tuning_6',['LambLisp Adaptive Tuning',['../index.html#autotoc_md37',1,'']]],
  ['adding_20native_20c_20code_20to_20lamblisp_7',['Adding native C++ code to LambLisp.',['../index.html#autotoc_md51',1,'']]],
  ['adding_20new_20fundamental_20features_8',['Scaling up by adding new fundamental features',['../index.html#autotoc_md34',1,'']]],
  ['advanced_20topics_9',['Advanced topics',['../index.html#autotoc_md41',1,'']]],
  ['advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_10',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['air_20updates_20without_20reboot_11',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md8',1,'']]],
  ['allocation_12',['Scaling up or down by controlling memory allocation.',['../index.html#autotoc_md36',1,'']]],
  ['and_20chicken_13',['What makes LambLisp different from small Lisps, such as Picobit and uLisp, or big Lisps, such as racket, ChezScheme, and chicken?',['../index.html#autotoc_md58',1,'']]],
  ['and_20continuation_20passing_20style_14',['Tail recursion and Continuation-Passing Style',['../index.html#autotoc_md64',1,'']]],
  ['and_20environments_15',['Dictionaries and environments',['../index.html#autotoc_md48',1,'']]],
  ['and_20list_20structures_16',['Cell Memory Model and List Structures',['../index.html#autotoc_md31',1,'']]],
  ['and_20macro_17',['lambda, nlambda, and macro',['../index.html#autotoc_md42',1,'']]],
  ['and_20objects_18',['Hash tables, environments, classes, dictionaries, and objects',['../index.html#autotoc_md46',1,'']]],
  ['and_20tail_20calls_19',['Tail recursion and tail-calls',['../index.html#autotoc_md12',1,'']]],
  ['and_20ulisp_20or_20big_20lisps_20such_20as_20racket_20chezscheme_20and_20chicken_20',['What makes LambLisp different from small Lisps, such as Picobit and uLisp, or big Lisps, such as racket, ChezScheme, and chicken?',['../index.html#autotoc_md58',1,'']]],
  ['api_20for_20new_20lisp_20primitives_21',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md7',1,'']]],
  ['applications_20as_20virtual_20machines_22',['Control Applications as Virtual Machines.',['../index.html#autotoc_md27',1,'']]],
  ['architecture_23',['Benefits of the LambLisp Scalable Architecture.',['../index.html#autotoc_md40',1,'']]],
  ['architecture_20internals_24',['LambLisp Architecture Internals',['../index.html#autotoc_md20',1,'']]],
  ['arduino_20libraries_25',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md5',1,'']]],
  ['are_20first_20class_20data_20types_26',['Procedures are first-class data types',['../index.html#autotoc_md13',1,'']]],
  ['are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_27',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md57',1,'']]],
  ['are_20the_20currently_20implemented_20features_28',['What are the currently implemented features?',['../index.html#autotoc_md61',1,'']]],
  ['are_20wrappers_20around_20hierarchical_20dictionaries_29',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md24',1,'']]],
  ['around_20hierarchical_20dictionaries_30',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md24',1,'']]],
  ['as_20picobit_20and_20ulisp_20or_20big_20lisps_20such_20as_20racket_20chezscheme_20and_20chicken_31',['What makes LambLisp different from small Lisps, such as Picobit and uLisp, or big Lisps, such as racket, ChezScheme, and chicken?',['../index.html#autotoc_md58',1,'']]],
  ['as_20racket_20chezscheme_20and_20chicken_32',['What makes LambLisp different from small Lisps, such as Picobit and uLisp, or big Lisps, such as racket, ChezScheme, and chicken?',['../index.html#autotoc_md58',1,'']]],
  ['as_20virtual_20machines_33',['Control Applications as Virtual Machines.',['../index.html#autotoc_md27',1,'']]],
  ['asked_20questions_34',['LambLisp Frequently Asked Questions',['../index.html#autotoc_md55',1,'']]]
];
