var searchData=
[
  ['naming_0',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['native_20code_1',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['native_20code_20generation_2',['Why not use LLVM for native code generation?',['../index.html#autotoc_md188',1,'']]],
  ['native_20code_20generator_20ncg_3',['Native Code Generator (NCG)',['../index.html#arch-ncg',1,'']]],
  ['navigation_4',['3.4 Waypoint Navigation',['../index.html#fwd-nav',1,'']]],
  ['ncg_5',['Native Code Generator (NCG)',['../index.html#arch-ncg',1,'']]],
  ['ncg_20compilation_6',['What is bytecode / NCG compilation?',['../index.html#autotoc_md175',1,'']]],
  ['need_7',['What you need',['../index.html#autotoc_md3',1,'']]],
  ['neopixel_8',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md94',1,'']]],
  ['network_20reach_9',['Network Reach',['../index.html#autotoc_md47',1,'']]],
  ['new_20lisp_20primitives_10',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#autotoc_md23',1,'']]],
  ['nlambda_11',['nlambda',['../index.html#autotoc_md55',1,'']]],
  ['nlambda_20and_20macro_12',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['no_20call_20with_20current_20continuation_13',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md182',1,'']]],
  ['no_20stop_20the_20world_20pauses_14',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['non_20blocking_20request_20poll_20model_15',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['non_20symbol_20keys_16',['Objects and non-symbol keys',['../index.html#autotoc_md61',1,'']]],
  ['not_17',['What is the same as Linux, and what is not',['../index.html#autotoc_md7',1,'']]],
  ['not_20exceptions_18',['2.4 Events, Not Exceptions',['../index.html#profibus-events',1,'']]],
  ['not_20run_20on_20embedded_20hardware_19',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['not_20use_20embedded_20python_20derivatives_20',['Why not use embedded Python derivatives?',['../index.html#autotoc_md186',1,'']]],
  ['not_20use_20llvm_20for_20native_20code_20generation_21',['Why not use LLVM for native code generation?',['../index.html#autotoc_md188',1,'']]],
  ['notes_22',['Notes',['../index.html#modbus-platform',1,'4. Platform Notes'],['../index.html#fwd-arch-notes',1,'7. Architecture Notes']]],
  ['notes_20music_20scm_23',['Musical Notes (&lt;span class=&quot;tt&quot;&gt;Music.scm&lt;/span&gt;)',['../index.html#autotoc_md120',1,'']]],
  ['now_24',['How do I try LambLisp right now?',['../index.html#autotoc_md160',1,'']]],
  ['now_20say_20so_25',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md200',1,'']]],
  ['numbers_26',['Numbers',['../index.html#autotoc_md133',1,'']]],
  ['numeric_20arrays_20array_27',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['numeric_20tower_28',['The Numeric Tower',['../index.html#autotoc_md131',1,'']]],
  ['nutshell_29',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md16',1,'']]],
  ['nvs_30',['The loader wire contract (NVS)',['../index.html#autotoc_md74',1,'']]]
];
