var searchData=
[
  ['table_20and_20hashing_20details_0',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['table_20sizing_20and_20collisions_1',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['tables_2',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['tags_3',['Error tags',['../index.html#autotoc_md116',1,'']]],
  ['tail_20calls_4',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['tail_20recursion_20and_20tail_20calls_5',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['task_20constructors_6',['Task Constructors',['../index.html#autotoc_md107',1,'']]],
  ['task_20queue_7',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['tcp_20tls_20vs_20serial_8',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['telemetry_20floor_20mapping_20demo_20telemetry_20scm_9',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md119',1,'']]],
  ['telemetry_20scm_10',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md119',1,'']]],
  ['that_20means_20has_20a_20socket_20must_20now_20say_20so_11',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md200',1,'']]],
  ['the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_12',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['the_20air_20updates_13',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['the_20air_20updates_20without_20reboot_14',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['the_20api_15',['5.2 The API',['../index.html#profinet-api',1,'']]],
  ['the_20baud_20ceiling_20and_20why_20it_20exists_16',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['the_20boot_20confirm_20rollback_20model_17',['The boot-confirm / rollback model',['../index.html#autotoc_md75',1,'']]],
  ['the_20bus_18',['2.1 Opening the Bus',['../index.html#profibus-open',1,'']]],
  ['the_20car_19',['the Car',['../index.html#fwd-jetson-waypoints',1,'4.3 Feeding Waypoints to the Car'],['../index.html#fwd-run-car',1,'6.2 Flash and Start the Car']]],
  ['the_20cloud_20server_20',['6.1 Start the Cloud Server',['../index.html#fwd-run-cloud',1,'']]],
  ['the_20compiled_20tier_20does_20not_20run_20on_20embedded_20hardware_21',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['the_20daemon_22',['5.1 Building the daemon',['../index.html#profinet-two-processes',1,'']]],
  ['the_20dictionary_20type_23',['The &lt;em&gt;dictionary&lt;/em&gt; type',['../index.html#arch-dict',1,'']]],
  ['the_20eval_20operation_24',['The eval Operation',['../index.html#autotoc_md84',1,'']]],
  ['the_20example_25',['the Example',['../index.html#fwd-run',1,'6. Running the Example'],['../index.html#fwd-extend',1,'7.3 Extending the Example']]],
  ['the_20four_20register_20tables_26',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['the_20freenove_204wd_20car_27',['the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car'],['../index.html#autotoc_md89',1,'Worked Example: Supervisory Control of the Freenove 4WD Car']]],
  ['the_20jetson_28',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['the_20lisp_20landscape_29',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md184',1,'']]],
  ['the_20loader_20wire_20contract_20nvs_30',['The loader wire contract (NVS)',['../index.html#autotoc_md74',1,'']]],
  ['the_20map_31',['4.5 Collecting the Map',['../index.html#fwd-jetson-collect',1,'']]],
  ['the_20memory_20footprint_32',['What is the memory footprint?',['../index.html#autotoc_md197',1,'']]],
  ['the_20non_20blocking_20request_20poll_20model_33',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['the_20numeric_20tower_34',['The Numeric Tower',['../index.html#autotoc_md131',1,'']]],
  ['the_20oblist_35',['The oblist',['../index.html#autotoc_md60',1,'']]],
  ['the_20queue_36',['The Queue',['../index.html#autotoc_md108',1,'']]],
  ['the_20repl_37',['the REPL',['../index.html#autotoc_md13',1,'Connect to the REPL'],['../index.html#autotoc_md8',1,'Using the REPL']]],
  ['the_20repository_38',['What&apos;s in the repository?',['../index.html#autotoc_md15',1,'']]],
  ['the_20robot_20stack_39',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['the_20same_20as_20linux_20and_20what_20is_20not_40',['What is the same as Linux, and what is not',['../index.html#autotoc_md7',1,'']]],
  ['the_20same_20scheme_20code_20run_20on_20all_20platforms_41',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md177',1,'']]],
  ['the_20serve_20loop_42',['3.4 The Serve Loop',['../index.html#modbus-serve-loop',1,'']]],
  ['the_20service_20loop_43',['2.3 The Service Loop',['../index.html#profibus-loop',1,'']]],
  ['the_20supervisor_20on_20the_20jetson_44',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['the_20supervisory_20architecture_45',['Role in the Supervisory Architecture',['../index.html#autotoc_md88',1,'']]],
  ['the_20universal_20glue_46',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['the_20world_20pauses_47',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['these_20run_20and_20what_20actually_20drives_20a_20pin_48',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['three_20tiers_49',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['tier_20does_20not_20run_20on_20embedded_20hardware_50',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['tiers_51',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['tiers_3a_20ast_20→_20bytecode_20→_20native_20code_52',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['time_20—_20bounded_20control_20cycle_53',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md43',1,'']]],
  ['time_20compilation_54',['Incremental, just-in-time compilation',['../index.html#autotoc_md26',1,'']]],
  ['time_20control_55',['Real-time control',['../index.html#autotoc_md18',1,'']]],
  ['time_20control_20system_56',['What is a real-time control system?',['../index.html#autotoc_md169',1,'']]],
  ['time_20garbage_20collection_57',['Adaptive real-time garbage collection',['../index.html#autotoc_md22',1,'']]],
  ['time_20guarantees_58',['Real-time Guarantees',['../index.html#arch-realtime',1,'']]],
  ['time_20lamblisp_59',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['time_20lisp_20for_20microprocessors_60',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['timers_20scm_61',['Timers (&lt;span class=&quot;tt&quot;&gt;Timers.scm&lt;/span&gt;)',['../index.html#autotoc_md102',1,'']]],
  ['timers_20timers_20scm_62',['Timers (&lt;span class=&quot;tt&quot;&gt;Timers.scm&lt;/span&gt;)',['../index.html#autotoc_md102',1,'']]],
  ['timing_20and_20system_63',['Timing and system',['../index.html#autotoc_md78',1,'']]],
  ['tls_20vs_20serial_64',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['to_20esp32_65',['Deploy to ESP32',['../index.html#deploy-esp32',1,'']]],
  ['to_20machine_66',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['to_20the_20car_67',['4.3 Feeding Waypoints to the Car',['../index.html#fwd-jetson-waypoints',1,'']]],
  ['to_20the_20repl_68',['Connect to the REPL',['../index.html#autotoc_md13',1,'']]],
  ['tools_69',['Diagnostics and Development Tools',['../index.html#autotoc_md71',1,'']]],
  ['tools_20llip_70',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['tower_71',['The Numeric Tower',['../index.html#autotoc_md131',1,'']]],
  ['transport_20and_20arq_20llip_20serial_20scm_72',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['transport_20scm_73',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['transports_3a_20tcp_20tls_20vs_20serial_74',['Transports: TCP/TLS vs Serial',['../index.html#llip-transports',1,'']]],
  ['try_20lamblisp_20on_20linux_75',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['try_20lamblisp_20on_20windows_76',['Quick Start: Try LambLisp on Windows',['../index.html#quick-start-windows',1,'']]],
  ['try_20lamblisp_20right_20now_77',['How do I try LambLisp right now?',['../index.html#autotoc_md160',1,'']]],
  ['tuning_78',['Tuning',['../index.html#arch-adaptive',1,'Memory and GC Tuning'],['../index.html#gc-tuning',1,'Runtime and GC Tuning']]],
  ['tuning_79',['GC and memory tuning',['../index.html#autotoc_md79',1,'']]],
  ['tuning_20parameters_80',['6.4 Tuning Parameters',['../index.html#fwd-run-tuning',1,'']]],
  ['tuning_3a_20stack_20size_20dma_20memory_20and_20pre_20reserve_81',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['twin_82',['Digital Twin',['../index.html#autotoc_md90',1,'']]],
  ['twin_20sync_83',['4.4 Digital Twin Sync',['../index.html#fwd-jetson-twin',1,'']]],
  ['type_84',['The &lt;em&gt;dictionary&lt;/em&gt; type',['../index.html#arch-dict',1,'']]],
  ['type_20system_85',['Type System',['../index.html#autotoc_md129',1,'']]],
  ['typed_20numeric_20arrays_20array_86',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['types_87',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]]
];
