var searchData=
[
  ['i_20o_0',['Arduino / Embedded I/O',['../index.html#llarduino',1,'']]],
  ['i_20try_20lamblisp_20right_20now_1',['How do I try LambLisp right now?',['../index.html#autotoc_md160',1,'']]],
  ['i_20update_20code_20without_20reflashing_2',['How do I update code without reflashing?',['../index.html#autotoc_md166',1,'']]],
  ['i_20use_20lamblisp_20without_20an_20rtos_3',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md195',1,'']]],
  ['i2c_20bus_20utilities_20i2c_20scm_4',['I2C Bus Utilities (&lt;span class=&quot;tt&quot;&gt;I2C.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['i2c_20gpio_20expander_20pcf8574_20scm_5',['I2C GPIO Expander (&lt;span class=&quot;tt&quot;&gt;PCF8574.scm&lt;/span&gt;)',['../index.html#autotoc_md103',1,'']]],
  ['i2c_20scm_6',['I2C Bus Utilities (&lt;span class=&quot;tt&quot;&gt;I2C.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['i2c_20wire_7',['I2C (Wire)',['../index.html#autotoc_md72',1,'']]],
  ['implementations_8',['Other Scheme Implementations',['../index.html#competitors',1,'']]],
  ['in_20a_20nutshell_9',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md16',1,'']]],
  ['in_20combination_20with_20c_20c_20on_20micro_20controllers_10',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['in_20the_20lisp_20landscape_11',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md184',1,'']]],
  ['in_20the_20repository_12',['What&apos;s in the repository?',['../index.html#autotoc_md15',1,'']]],
  ['in_20the_20supervisory_20architecture_13',['Role in the Supervisory Architecture',['../index.html#autotoc_md88',1,'']]],
  ['in_20time_20compilation_14',['Incremental, just-in-time compilation',['../index.html#autotoc_md26',1,'']]],
  ['incremental_20hot_20reload_15',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['incremental_20just_20in_20time_20compilation_16',['Incremental, just-in-time compilation',['../index.html#autotoc_md26',1,'']]],
  ['incremental_20over_20the_20air_20updates_20without_20reboot_17',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['initiated_20serving_20llip_20transport_20scm_18',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['input_20and_20output_19',['Input and Output',['../index.html#autotoc_md153',1,'']]],
  ['instead_20of_20scheme_20',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md180',1,'']]],
  ['integers_20bignums_21',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['integration_22',['Integration',['../index.html#arch-cpp',1,'C++ Integration'],['../index.html#cuda-integration',1,'CUDA Integration']]],
  ['integration_20and_20operation_23',['Integration and Operation',['../index.html#autotoc_md190',1,'']]],
  ['interaction_20protocol_24',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['interface_25',['Interface',['../index.html#modbus',1,'LambLisp Modbus Interface'],['../index.html#fieldbus',1,'LambLisp PROFIBUS and PROFINET Interface'],['../index.html#autotoc_md155',1,'System Interface']]],
  ['internals_26',['LambLisp Architecture Internals',['../index.html#autotoc_md32',1,'']]],
  ['internals_20and_20c_20api_27',['Language Internals and C++ API',['../index.html#autotoc_md53',1,'']]],
  ['interoperate_20with_20c_20c_20code_28',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md193',1,'']]],
  ['interpreter_20compiler_20organization_29',['Interpreter &amp;amp; compiler organization',['../index.html#arch-interp',1,'']]],
  ['interrupt_20latency_20—_20sub_20microsecond_20isr_30',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md44',1,'']]],
  ['io_20device_31',['PROFINET IO-Device',['../index.html#autotoc_md115',1,'']]],
  ['is_20a_20hierarchical_20dictionary_32',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['is_20a_20real_20time_20control_20system_33',['What is a real-time control system?',['../index.html#autotoc_md169',1,'']]],
  ['is_20bytecode_20ncg_20compilation_34',['What is bytecode / NCG compilation?',['../index.html#autotoc_md175',1,'']]],
  ['is_20it_20called_20lamblisp_20instead_20of_20scheme_35',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md180',1,'']]],
  ['is_20lamblisp_36',['How fast is LambLisp?',['../index.html#autotoc_md173',1,'']]],
  ['is_20lamblisp_20open_20source_37',['Is LambLisp open source?',['../index.html#autotoc_md164',1,'']]],
  ['is_20llip_38',['What is LLIP?',['../index.html#autotoc_md171',1,'']]],
  ['is_20not_39',['What is the same as Linux, and what is not',['../index.html#autotoc_md7',1,'']]],
  ['is_20the_20memory_20footprint_40',['What is the memory footprint?',['../index.html#autotoc_md197',1,'']]],
  ['is_20the_20same_20as_20linux_20and_20what_20is_20not_41',['What is the same as Linux, and what is not',['../index.html#autotoc_md7',1,'']]],
  ['isr_42',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md44',1,'']]],
  ['it_43',['it',['../index.html#autotoc_md4',1,'Get it'],['../index.html#autotoc_md5',1,'Run it']]],
  ['it_20called_20lamblisp_20instead_20of_20scheme_44',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md180',1,'']]],
  ['it_20exists_45',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]]
];
