var searchData=
[
  ['waypoint_20navigation_0',['3.4 Waypoint Navigation',['../index.html#fwd-nav',1,'']]],
  ['waypoints_20to_20the_20car_1',['4.3 Feeding Waypoints to the Car',['../index.html#fwd-jetson-waypoints',1,'']]],
  ['what_20actually_20drives_20a_20pin_2',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['what_20are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_3',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['what_20happens_20at_20startup_4',['What Happens at Startup',['../index.html#autotoc_md14',1,'']]],
  ['what_20hardware_20does_20lamblisp_20run_20on_5',['What hardware does LambLisp run on?',['../index.html#autotoc_md162',1,'']]],
  ['what_20is_20a_20real_20time_20control_20system_6',['What is a real-time control system?',['../index.html#autotoc_md169',1,'']]],
  ['what_20is_20bytecode_20ncg_20compilation_7',['What is bytecode / NCG compilation?',['../index.html#autotoc_md175',1,'']]],
  ['what_20is_20llip_8',['What is LLIP?',['../index.html#autotoc_md171',1,'']]],
  ['what_20is_20not_9',['What is the same as Linux, and what is not',['../index.html#autotoc_md7',1,'']]],
  ['what_20is_20the_20memory_20footprint_10',['What is the memory footprint?',['../index.html#autotoc_md197',1,'']]],
  ['what_20is_20the_20same_20as_20linux_20and_20what_20is_20not_11',['What is the same as Linux, and what is not',['../index.html#autotoc_md7',1,'']]],
  ['what_20s_20in_20the_20repository_12',['What&apos;s in the repository?',['../index.html#autotoc_md15',1,'']]],
  ['what_20you_20get_13',['1. What You Get',['../index.html#fieldbus-what-you-get',1,'']]],
  ['what_20you_20need_14',['What you need',['../index.html#autotoc_md3',1,'']]],
  ['where_20does_20lamblisp_20sit_20in_20the_20lisp_20landscape_15',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md184',1,'']]],
  ['where_20these_20run_20and_20what_20actually_20drives_20a_20pin_16',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['why_20is_20it_20called_20lamblisp_20instead_20of_20scheme_17',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md180',1,'']]],
  ['why_20it_20exists_18',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['why_20lamblisp_19',['Why &lt;em&gt;LambLisp&lt;/em&gt;?',['../index.html#why-lamblisp',1,'']]],
  ['why_20lisp_20',['Why Lisp?',['../index.html#autotoc_md17',1,'']]],
  ['why_20no_20call_20with_20current_20continuation_21',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md182',1,'']]],
  ['why_20not_20use_20embedded_20python_20derivatives_22',['Why not use embedded Python derivatives?',['../index.html#autotoc_md186',1,'']]],
  ['why_20not_20use_20llvm_20for_20native_20code_20generation_23',['Why not use LLVM for native code generation?',['../index.html#autotoc_md188',1,'']]],
  ['why_20the_20compiled_20tier_20does_20not_20run_20on_20embedded_20hardware_24',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['why_20three_20tiers_25',['7.1 Why Three Tiers?',['../index.html#fwd-why-three-tiers',1,'']]],
  ['widely_20recognized_20scheme_20language_20specification_26',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md20',1,'']]],
  ['wifi_27',['WiFi',['../index.html#autotoc_md73',1,'']]],
  ['wifi_20access_20point_20softap_28',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['wifi_20station_20—_20advanced_29',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['windows_30',['Quick Start: Try LambLisp on Windows',['../index.html#quick-start-windows',1,'']]],
  ['wire_31',['I2C (Wire)',['../index.html#autotoc_md72',1,'']]],
  ['wire_20bus_32',['OneWire (1-Wire Bus)',['../index.html#onewire',1,'']]],
  ['wire_20contract_20nvs_33',['The loader wire contract (NVS)',['../index.html#autotoc_md74',1,'']]],
  ['wire_20format_34',['Wire Format',['../index.html#autotoc_md81',1,'']]],
  ['wiring_35',['4. RS-485 Wiring',['../index.html#profibus-wiring',1,'']]],
  ['with_20c_20c_20code_36',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md193',1,'']]],
  ['with_20c_20c_20on_20micro_20controllers_37',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md191',1,'']]],
  ['with_20c_20code_38',['Runtime collaboration with C++ code',['../index.html#autotoc_md30',1,'']]],
  ['with_20current_20continuation_39',['Why no &lt;span class=&quot;tt&quot;&gt;call-with-current-continuation&lt;/span&gt;?',['../index.html#autotoc_md182',1,'']]],
  ['with_20real_20time_20lamblisp_40',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['with_20the_20freenove_204wd_20car_41',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['without_20an_20rtos_42',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md195',1,'']]],
  ['without_20reboot_43',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['without_20reflashing_44',['How do I update code without reflashing?',['../index.html#autotoc_md166',1,'']]],
  ['work_20—_20deferred_20task_20queue_45',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['worked_20example_3a_20autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_46',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]],
  ['worked_20example_3a_20supervisory_20control_20of_20the_20freenove_204wd_20car_47',['Worked Example: Supervisory Control of the Freenove 4WD Car',['../index.html#autotoc_md89',1,'']]],
  ['worked_20examples_48',['Worked Examples',['../index.html#worked-examples',1,'']]],
  ['world_20pauses_49',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['wrappers_20around_20hierarchical_20dictionaries_50',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['wrappers_20sonar_20scm_51',['Sonar Convenience Wrappers (&lt;span class=&quot;tt&quot;&gt;Sonar.scm&lt;/span&gt;)',['../index.html#autotoc_md106',1,'']]],
  ['write_20callbacks_52',['3.5 Write Callbacks',['../index.html#modbus-write-callbacks',1,'']]],
  ['ws2812_20addressable_20led_20strip_20neopixel_53',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md94',1,'']]],
  ['ws2812_20scm_54',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md99',1,'']]]
];
