var searchData=
[
  ['raspberry_20pi_20libgpiod_0',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['reach_1',['Reach',['../index.html#autotoc_md46',1,'Group A — Reach'],['../index.html#autotoc_md47',1,'Network Reach']]],
  ['real_20pins_20on_20a_20jetson_20or_20raspberry_20pi_20libgpiod_2',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['real_20time_20control_3',['Real-time control',['../index.html#autotoc_md18',1,'']]],
  ['real_20time_20control_20system_4',['What is a real-time control system?',['../index.html#autotoc_md169',1,'']]],
  ['real_20time_20garbage_20collection_5',['Adaptive real-time garbage collection',['../index.html#autotoc_md22',1,'']]],
  ['real_20time_20guarantees_6',['Real-time Guarantees',['../index.html#arch-realtime',1,'']]],
  ['real_20time_20lamblisp_7',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['real_20time_20lisp_20for_20microprocessors_8',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['reboot_9',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['recognized_20scheme_20language_20specification_10',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md20',1,'']]],
  ['recursion_20and_20tail_20calls_11',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['reference_12',['Reference',['../index.html#modbus-quickref',1,'5. Quick Reference'],['../index.html#fieldbus-quickref',1,'8. Quick Reference']]],
  ['reflashing_13',['How do I update code without reflashing?',['../index.html#autotoc_md166',1,'']]],
  ['register_20accessors_14',['3.3 Register Accessors',['../index.html#modbus-register-accessors',1,'']]],
  ['register_20tables_15',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['reload_16',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['render_17',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['repl_18',['REPL',['../index.html#autotoc_md13',1,'Connect to the REPL'],['../index.html#autotoc_md8',1,'Using the REPL']]],
  ['repository_19',['What&apos;s in the repository?',['../index.html#autotoc_md15',1,'']]],
  ['request_20',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md111',1,'']]],
  ['request_20poll_20model_21',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['requesting_20a_20coverage_20plan_22',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['reserve_23',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['reuse_20of_20existing_20c_20arduino_20libraries_24',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md21',1,'']]],
  ['right_20now_25',['How do I try LambLisp right now?',['../index.html#autotoc_md160',1,'']]],
  ['ring_20service_20leds_20scm_26',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md100',1,'']]],
  ['robot_20stack_27',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['role_20in_20the_20supervisory_20architecture_28',['Role in the Supervisory Architecture',['../index.html#autotoc_md88',1,'']]],
  ['rollback_20model_29',['The boot-confirm / rollback model',['../index.html#autotoc_md75',1,'']]],
  ['rs_20485_20wiring_30',['4. RS-485 Wiring',['../index.html#profibus-wiring',1,'']]],
  ['rtos_31',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md195',1,'']]],
  ['run_20and_20what_20actually_20drives_20a_20pin_32',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['run_20it_33',['Run it',['../index.html#autotoc_md5',1,'']]],
  ['run_20on_34',['What hardware does LambLisp run on?',['../index.html#autotoc_md162',1,'']]],
  ['run_20on_20all_20platforms_35',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md177',1,'']]],
  ['run_20on_20embedded_20hardware_36',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['run_20the_20supervisor_20on_20the_20jetson_37',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['running_20from_20any_20directory_38',['Running from any directory',['../index.html#autotoc_md6',1,'']]],
  ['running_20the_20example_39',['6. Running the Example',['../index.html#fwd-run',1,'']]],
  ['runtime_20and_20gc_20tuning_40',['Runtime and GC Tuning',['../index.html#gc-tuning',1,'']]],
  ['runtime_20collaboration_20with_20c_20code_41',['Runtime collaboration with C++ code',['../index.html#autotoc_md30',1,'']]]
];
